### ISSUE TITLE
Ajustar template de emails dos alertas da Minha BVS

### ISSUE THREAD

**Issue by wilsonmoura** [bireme/my-vhl-alerts#11]

**Comment by wilsonmoura** [comment]
@pierrima Link de acesso ao template: http://platserv2.teste.bvsalud.org/alerts.html

**Comment by wilsonmoura** [comment]
@pierrima Nesse template, também será necessário exibir para o usuário um link com opção de cancelamento do envio de alertas.

**Comment by wilsonmoura** [comment]
@pierrima Ficamos no aguardo da proposta de layout do template de emails que será implementado nos alertas da Minha BVS.

**Comment by wilsonmoura** [comment]
Ajustes realizados pela @pierrima foram implementados.

**Comment by renatomurasaki** [comment]
Wilson, sugiro a seguinte mudança no template da mensagem do alerta:

1. Estrutura da mensagem de alerta (de cima para baixo):
 - Banner
 - `<Saudação> <Nome do Usuário>`
 - TEXTO 1
 - `<ALERT>` como já está no momento
 - TEXTO 2
 - TEXTO 3
 - TEXTO 4
 - TEXTO 5

2. Conteúdo
 - `<Saudação>` depende do idioma e pode ser {Prezado, Prezada, Estimado, Estimada e Dear}
 - `<Nome do Usuário>` vem da base de dados de acordo com o ID do usuário
- TEXTO 1: Seguem abaixo os novos documentos disponíveis na Biblioteca Virtual em Saúde que são relacionados ao(s) seu(s) tema(s) de interesse registrados nos serviços personalizados MinhaBVS.
 - TEXTO 2: Você recebeu esta mensagem por ser usuário da MinhaBVS e por aceitar o recebimento de novidades deste serviço por e-mail.
 - TEXTO 3: Atenciosamente, Equipe BIREME/OPAS/OMS
 - TEXTO 4: Deixar de receber este tipo de e-mail (link para o serviço de descadastramento)
 - TEXTO 5: Não sou usuário da MinhaBVS (link para http://feedback.bireme.org/feedback/wp-bvs-plugin?version=1.0&error=1)

**Comment by wilsonmoura** [comment]
Resolvido em 79f2bf47510acf19e26695d6980c20e9c4ea23cd.
