### ISSUE TITLE
Campanha 1 - Envio para usuários inativos (Redes Sociais)

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/my-vhl-alerts#22]
Criar multiplas campanhas, priorizando os usuários inativos de rede social do último trimestre (abril, maio, junho). Após avaliação do comportamneto desta campanha, enviar para os demais meses.

A mensagem deve explicar que o usuário criou conta no MinhaBVS na data X, que ele ainda não aceitou a política de privacidade e termos de uso, solicitando que ele clique no link de login para finalizar o cadastro.

**Comment by wilsonmoura** [comment]
Usuário importados da Minha BVS para o Mautic com base na seguinte query:

`SELECT CONCAT(userEmail, ',', userFirstName, ',', userLastName, ',', userSource, 1) AS sn_inatives FROM users WHERE userSource IN('facebook', 'google') AND agreement_date = '' AND last_login BETWEEN '2018-03-31' AND '2018-07-01'`

**Comment by wilsonmoura** [comment]
**Indicadores da campanha**

Total (pré-envio): 1689
Total (pós-envio): 1647
Total de emails lidos: 489

**Conversão de usuários ativos**

1689 - 1647 = 42 usuários
42 / 489 = 0,0858 = 8,58%
