### ISSUE TITLE
Campanha 2 - Envio para usuários LDAP inativos

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/my-vhl-alerts#23]
Seguir a mesma estratégia do #22, porém para os usuários inativos via LDAP

**Comment by wilsonmoura** [comment]
Usuário importados da Minha BVS para o Mautic com base na seguinte query:

`SELECT CONCAT(u.userEmail, ',', u.userFirstName, ',', u.userLastName, ',', u.userSource, ',', IFNULL(u.userCountry,NULL), ',', 1) AS ldap_inatives FROM users AS u INNER JOIN userConfirm AS uc ON u.sysUID = uc.sysUID WHERE u.userSource = 'ldap' AND u.agreement_date <> '' AND u.last_login IS NULL AND uc.action = 'user' AND (uc.creation_date BETWEEN '2018-03-31' AND '2018-07-01' OR uc.confirmation_date BETWEEN '2018-03-31' AND '2018-07-01')`

**Comment by wilsonmoura** [comment]
**Indicadores da campanha**

Total (pré-envio): 992
Total (pós-envio): 969
Total de emails lidos: 379

**Conversão de usuários ativos**

992 - 969 = 23 usuários
23 / 379 = 0,0606 = 6,06%
