### ISSUE TITLE
Avaliar como o Mautic será alimentado com informação de usuário, temas de interesse e documentos relacionados

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/my-vhl-alerts#8]

**Comment by wilsonmoura** [comment]
Atividades:
- Os usuários serão adicionados via API do Mautic
- Os templates de email listando os temas de interesse e seus respectivos documentos relacionados serão incorporados nos alertas com apoio de um plugin do Mautic que será desenvolvido para gerar um token customizado.

**Comment by wilsonmoura** [comment]
Dependências #12 e #13

**Comment by wilsonmoura** [comment]
Dependências finalizadas.
